"""Chapter-local teaching contracts for the executable demos.

Each entry describes only the responsibility earned at that checkpoint.  The
registry is deliberately data-only so presentation stays separate from domain
behavior and branch projection can retain only the entries earned so far.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ChapterStory:
    title: str
    question: str
    introduced: str
    problem: str
    previously_earned: str
    new_in_chapter: str
    makes_possible: str


CHAPTER_STORIES = {
    1: ChapterStory(
        "When a Good Answer Is Not the Work",
        "Can a plausible answer prove that the investigation work is complete?",
        "Observable completion conditions",
        "A persuasive answer can hide missing evidence or failed work.",
        "Nothing — this is the foundation.",
        "Answer, evidence, action, and result stay separate.",
        "Completion can depend on recorded evidence and an observed result.",
    ),
    2: ChapterStory(
        "What This Investigation May Touch",
        "Can permitted work be defined before any outside system is contacted?",
        "Observation and action perimeter",
        "A useful request can still target the wrong operation, system, or environment.",
        "Observable completion conditions",
        "Declared operations, sources, environments, resources, and selectors.",
        "Forbidden work is refused before an outside call can begin.",
    ),
    3: ChapterStory(
        "When Permitted Work Still Wastes Time",
        "Can the model choose useful work without gaining authority to execute it?",
        "Bounded model choice",
        "Several observations may be permitted while only one closes the current gap.",
        "Completion conditions · deterministic scope",
        "A model selects one declared observation; application code performs it.",
        "Flexible judgment can guide work without becoming the execution boundary.",
    ),
    4: ChapterStory(
        "When Evidence Changes the Shape of the Work",
        "Can newly observed evidence reveal work that was not knowable earlier?",
        "Evidence-driven task graph",
        "A static checklist cannot represent resources discovered during investigation.",
        "Completion · scope · bounded model choice",
        "Recorded results move tasks and create only evidence-justified work.",
        "The investigation can expand without allowing the model to invent topology.",
    ),
    5: ChapterStory(
        "What the Model Sees and What May Run",
        "Can a model proposal become executable without treating its prose as evidence?",
        "Decision surface and proposal admission",
        "A model response can be stale, malformed, unsupported, or persuasive but false.",
        "Evidence-driven tasks and bounded choice",
        "Current context, typed proposals, readiness checks, and deterministic admission.",
        "Only a current declared task crosses from judgment into runtime execution.",
    ),
    6: ChapterStory(
        "When Judgment Becomes a Dependency",
        "Can model unavailability consume a bounded, observable amount of the run?",
        "Decision budget and attempt ledger",
        "Retries can silently exhaust time, cost, and the investigation deadline.",
        "Typed proposal admission",
        "Call, retry, elapsed-time, and usage limits with recorded stop reasons.",
        "The run can fail closed when judgment is unavailable or exhausted.",
    ),
    7: ChapterStory(
        "Keeping Changed Work Alive After a Restart",
        "Can the investigation resume without reconstructing state from memory?",
        "Durable workflow state",
        "A process restart can erase evidence, ready work, and consumed decision budget.",
        "Bounded decisions · evidence-driven graph",
        "The incident, graph, hypothesis history, and attempt ledger persist together.",
        "Recovery resumes from recorded state instead of replaying uncertain work.",
    ),
    8: ChapterStory(
        "Trying Again Without Doing It Twice",
        "Can a lost response be retried without applying the report update twice?",
        "Idempotent effect application",
        "The caller may not know whether an effect committed before its response was lost.",
        "Durable workflow state",
        "Immutable intent, stable idempotency key, and atomic effect deduplication.",
        "The same logical effect can be retried safely after transport uncertainty.",
    ),
    9: ChapterStory(
        "When an Attempt Ends but Its Effect Is Unknown",
        "Can a local timeout stay separate from the outside effect's real outcome?",
        "Unknown-outcome reconciliation",
        "Stopping the local wait does not prove that dispatched outside work stopped.",
        "Idempotent effects",
        "Attempt outcome, effect outcome, and later reconciliation remain distinct.",
        "Unknown effects can be resolved before the workflow decides whether to retry.",
    ),
    10: ChapterStory(
        "Carrying Forward Only What Helps",
        "Can prior knowledge help without becoming evidence for the current incident?",
        "Scoped reviewed-memory retrieval",
        "Unbounded or unrelated history can crowd out current evidence and distort causality.",
        "Durable state · reconciled effects",
        "Safety filtering, ranking, and explicit record and byte budgets.",
        "Reviewed lessons can guide judgment while current evidence remains authoritative.",
    ),
    11: ChapterStory(
        "Keeping a Long Investigation on Course",
        "Can ready but irrelevant work be kept outside the current milestone?",
        "Persistent task spine",
        "A growing graph can drift into permitted work that no longer serves the objective.",
        "Scoped memory · evidence-driven tasks",
        "Purpose, milestone, current question, allowed tasks, and transition evidence.",
        "The run preserves direction across many individually valid decisions.",
    ),
    12: ChapterStory(
        "Sharing Work Without Losing Ownership",
        "Can another worker take over without accepting a stale owner's late result?",
        "Leased ownership with fencing",
        "Concurrent or restarted workers can both believe they own the same task.",
        "Durable task spine",
        "Expiring claims and monotonically increasing fencing tokens.",
        "Work can be reassigned while stale completions remain unable to commit.",
    ),
    13: ChapterStory(
        "Depending on Systems That May Be Wrong",
        "Can dependency output be useful data without becoming trusted instruction?",
        "Dependency evidence admission",
        "External results may be stale, incomplete, malformed, or instruction-bearing.",
        "Fenced ownership · bounded context",
        "Freshness, completeness, exact-field, and typed-value validation.",
        "Only admitted dependency facts can reach the decision surface.",
    ),
    14: ChapterStory(
        "Running Generated Work Inside a Boundary",
        "Can generated analysis run without inheriting the investigation's authority?",
        "Execution sandbox and artifact admission",
        "Generated code would otherwise inherit credentials, filesystem, network, and live state.",
        "Task spine · fenced ownership · evidence quality",
        "Immutable request, restricted execution, and validated output artifact.",
        "Flexible analysis can run while authority and admission stay in application code.",
    ),
    15: ChapterStory(
        "Choosing How Much Judgment a Decision Needs",
        "Can each decision use the smallest judgment source that satisfies its requirements?",
        "Requirement-based judgment routing",
        "One model profile cannot optimize every latency, cost, capability, and data constraint.",
        "Bounded generated analysis",
        "Decision requirements are matched against declared judgment-source profiles.",
        "Routing becomes a deterministic fit decision rather than a model preference.",
    ),
    16: ChapterStory(
        "When New Evidence Changes What Comes Next",
        "Can future work change without rewriting commitments already completed?",
        "Evidence-driven plan replacement",
        "New evidence can invalidate future steps while completed work must remain durable.",
        "Judgment routing · durable direction",
        "Versioned plans preserve succeeded commitments and replace only future work.",
        "The investigation can replan honestly without erasing its history.",
    ),
    17: ChapterStory(
        "When Useful Contributions Do Not Add Up",
        "Can specialist results be joined without mistaking partial work for completion?",
        "Delegation and checked joins",
        "Individually useful specialist returns may be stale, incomplete, or mutually insufficient.",
        "Versioned plans",
        "Exact assignments, evidence-backed returns, and an explicit join contract.",
        "Parallel contributions become one proposal only after every obligation is met.",
    ),
    18: ChapterStory(
        "Waiting Safely for a Consequential Decision",
        "Can a later approval be proven to authorize the exact stored intent?",
        "Durable intent-bound approval",
        "A bare approval can arrive late or refer to different content than the pending effect.",
        "Checked specialist join",
        "Persisted intent digest, expiry, correlation, and replay-safe approval signals.",
        "Human approval survives waiting without becoming an ambiguous yes.",
    ),
    19: ChapterStory(
        "Knowing Who May Do What",
        "Can verified identity authorize only one exact delegated effect?",
        "Verified identity and delegated authority",
        "Authentication alone does not prove authority for this operation and resource.",
        "Durable exact-intent approval",
        "Verified session claims bind a scoped, expiring grant to the approved effect.",
        "Authority is explicit, narrow, and re-checkable at execution time.",
    ),
    20: ChapterStory(
        "Making Rules Independent of Wording",
        "Can equivalent requests receive the same decision without parsing persuasive prose?",
        "Structured policy decision",
        "Natural-language wording is unstable and unsafe as the policy decision surface.",
        "Verified delegated authority",
        "Versioned rules evaluate typed facts and return explicit reasons.",
        "Policy stays deterministic even when user wording changes.",
    ),
    21: ChapterStory(
        "Enforcing Rules Where Effects Happen",
        "Can the report store refuse work even when an earlier layer made a mistake?",
        "Effect-time enforcement",
        "Approval and policy checks can become stale or be bypassed before the write.",
        "Intent approval · authority · structured policy",
        "The effect boundary rechecks current facts, intent, policy version, and resource version.",
        "No upstream success can substitute for guardrails at the actual write.",
    ),
    22: ChapterStory(
        "Seeing the Path, Not Only the Answer",
        "Can a production run be reconstructed without storing raw sensitive content?",
        "Semantic execution trace",
        "A final answer cannot reveal which evidence, decisions, and effects produced it.",
        "Effect-time enforcement",
        "Ordered digest-bound events preserve path, provenance, timing, and outcome.",
        "Operators can reconstruct behavior without exposing raw request or evidence content.",
    ),
    23: ChapterStory(
        "Judging the Whole Trajectory",
        "Can a useful-looking answer fail because the path that produced it was unsafe?",
        "Trajectory evaluation",
        "Answer-only scoring ignores missing evidence, forbidden actions, and failed outcomes.",
        "Semantic execution trace",
        "Evidence, path, action, and outcome dimensions judge the same executed trace.",
        "Quality becomes a property of the whole run rather than its final prose.",
    ),
    24: ChapterStory(
        "Making Evaluation a Release Boundary",
        "Can a candidate be prevented from shipping when its campaign is empty or unsafe?",
        "Fail-closed release gate",
        "Evaluation metrics are advisory until they control whether a candidate may launch.",
        "Multi-dimensional trajectory evaluation",
        "Quality, safety, latency, and unit thresholds require real campaign evidence.",
        "Release becomes an executable decision that fails closed.",
    ),
    25: ChapterStory(
        "Observing Production Without Exposing It",
        "Can operators see useful behavior without receiving raw sensitive evidence?",
        "Redacted operational view",
        "Production visibility can leak the very data and prompts the system must protect.",
        "Semantic traces · release evidence",
        "Operational projections expose counts, digests, timing, units, and outcomes only.",
        "Teams can diagnose behavior while data minimization remains intact.",
    ),
    26: ChapterStory(
        "Testing What Authored Cases Missed",
        "Can deliberate variations expose failures hidden by the happy path?",
        "Variation campaign",
        "A small authored suite cannot cover model, dependency, timing, and evidence variation.",
        "Redacted operations · trajectory evaluation",
        "Stable variation plans execute the real Orders journey across controlled changes.",
        "Robustness claims are supported by behavior across meaningful variation.",
    ),
    27: ChapterStory(
        "Turning Incidents Into Boundaries",
        "Can one production failure become a durable, owned regression contract?",
        "Incident-to-regression promotion",
        "A retrospective lesson is easy to forget if it never changes executable acceptance.",
        "Variation campaigns",
        "Failure signatures, owners, cases, and replay verification are stored together.",
        "A corrected path must satisfy the boundary that the original incident violated.",
    ),
}
